### ISSUE TITLE
Profile physics 2 same clusters

### ISSUE THREAD

**Issue by slimeradio** [TorchAPI/Profiler#14]
Hi! On screenshot you can see, that there are 2 same clusters. 
(Running 3 servers on 1 PC, with same star system)
Can you say anything about it?

Is it an output bug, or Keen twice simulating same sector?))

![2020-03-26_22-12-52](https://user-images.githubusercontent.com/13731974/77687281-32c5b880-6faf-11ea-82c4-2d1d5f0c0d27.png)

**Comment by Jimmacle** [comment]
The profiler is no longer guaranteed to work correctly because of how Keen changed the update system last major. We aren't currently looking at fixing it.

**Comment by Equinox-** [comment]
Cluster profiling was removed.
