### ISSUE TITLE
Programmable Blocks not working when Profiler installed

### ISSUE THREAD

**Issue by LordTylus** [TorchAPI/Profiler#9]
- [x] Verify that this issue is related to Profiler 
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.72 **SE Version:** 1.192.020 **Profiler Version:** v2.0.2.4-7-g28de2ed

### Expected Behavior
Programmable Blocks run their scripts normally as always before. 

### Observed Behavior
If profiler is installed Scripts wont get executed. You can compile them and get "Compuilation successful" but when tryping to run it you always get "Assembly not Found"

### Steps to Reproduce
1. Start server
2. Login 
3. Build PB
4. Run simple Script like Echo("lol");
5. Compile > works
6. Run > Assembly not found

### Other Information
I dont have many Logfiles, but there were some additional information on discord. Regarding Profiler Breaking the ModAPI

11:57:36.5506 [ERROR]  Keen:       Error during ModAPI initialization: Empty path name is not legal.

kamikaze0310heute um 19:05 Uhr
ok, well if found an issue with the profiler plugin, did lots of testing to make sure but its giving me errors in the log saying failing to compile mods. Mods still seem to load but it i've noticed that they fail to be able to read/write from xml config (if they have one). Once the plugin is removed, no more errors and all is well.
log incoming

https://discordapp.com/channels/230191591640268800/360599679714590743/614505468651634742

https://cdn.discordapp.com/attachments/360599679714590743/614505866653073480/log.txt

**Comment by daniel-kukiela** [comment]
Can confirm that.
I did a lot of testing and came to the same conclusion.
Speaking of mods, Nanite Control Facility does not work when Profiler is being installed.

**Comment by smooreace** [comment]
That mod is crap anyway. No loss! There are far better alternatives... that
work!

**Comment by Jimmacle** [comment]
The Profiler plugin is pretty broken and we don't have a timeline for fixing it; if you had it installed you should remove it until further notice.

**Comment by daniel-kukiela** [comment]
@smooreace Maybe not the right place to ask, but can you say more on that? What alternatives should I look at? Thank you in advance.

@Jimmacle Thank you for fast response.

**Comment by Baughn** [comment]
Well, that explains one or two things. Please let us know when it's working -- it's fairly critical to keep a server running.

**Comment by N1Ran** [comment]
It's fixed on latest version. Check the version you have installed

**Comment by N1Ran** [comment]
Jimm, close this issue please. I have to no authority to do so
